### PR TITLE
Field access

### PR DESCRIPTION
**Pull request by phgross**
I rebuilt the field accessing in the atschemaupdater, so that it uses the field accessor and mutator instead of direct field access in the schemaupdater.

Also added a .gitignore.

### CODE REVIEW

**Comment by mjpieters** [comment]
Sorry, no, that's not a good idea. SchemaExtension fields for example do not have an accessor or mutator set.

What is your usecase? It may be valid to use the accessor or mutator if one is set, but I'd have to think some more about that.

I'll see about pulling in the .gitignore separately. My own global .gitignore already includes most of that but this repo can do with an explicit set.

**Comment by phgross** [comment]
Our problem is that the `allowDiscussion` value seems not to be set properly:
The mutator of `allowDiscussion` stores the value in `portal_discussion` and not in the default storage.
When doing something like `field.set(obj, True)` it does something like `field.getStorage().set(True)` (not sure about the exact call), but it does not call the mutator of `allowDiscussion` and only the mutator updates `portal_discussion`.

See the mutator method here: https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/ExtensibleMetadata.py#L272

As result we have this behavior:
`field.get(obj)` says `True`
but `obj.isDiscussable()` says `False`.

So the simplest way to fix this would be to call the mutator. Maybe we could agree on a safe solution like testing for a mutator and using `field.set` as fallback?

**Comment by mjpieters** [comment]
Yes, I see what you mean. The proper way to solve this then is to indeed test to see if there is a mutator defined and use that if present, and do the same for the accessor.

I'd define two helper methods, get and set:

``` python
def get(field, obj):
    if field.accessor is not None:
        return getattr(obj, field.accessor)()
    return field.get(obj)

def set(field, obj, val):
    if field.mutator is not None:
        getattr(obj, field.mutator)(val)
    field.set(obj, val)
```

That way we can keep the loop code clean. I am also now pondering if this code should not be using `getRaw` instead of `get`, but that could be dealt with separately (e.g. by me if need be).

Do you mind extending the tests a little to include something exercising accessor and mutator usage?

**Comment by mjpieters** [comment]
I've pulled in the .gitignore commit now.

**Comment by phgross** [comment]
I've updated the branch with the discussed changes including updating the tests.

The tests with the Plone 3.x buildout threw errors, but it should not be related with my changes. I got:

``` python
  File ".../plone.app.transmogrifier/src/plone/app/transmogrifier/tests.py", line 409, in reindexObjectSetup
    from Products.Archetypes.interfaces import IBaseObject
ImportError: cannot import name CatalogAware
```

Tests again Plone 4.0 passed fine.

**Comment by mjpieters** [comment]
Thanks! I've merged your commit.

**Pull request merged**
